#!/bin/sh

echo "Starting s3 server"
REMOTE_MANAGEMENT_DISABLE=1 npm start | tee &

# wait for server to be ready
bash wait_for_local_port.bash 8000 40

# these are the default access keys for zenko/cloudserver
export AWS_ACCESS_KEY_ID=accessKey1
export AWS_SECRET_ACCESS_KEY=verySecretKey1

# Copy audio
# NOTE: we load audition files and download files (mp3 only).
echo "Creating Bucket"
aws --endpoint http://localhost:8000 s3 mb s3://media-local

echo "Start Loading Audio"
aws --endpoint http://localhost:8000 s3 cp /bucket-data/ s3://media-local/ --acl 'public-read' --recursive

# echo "Setting CORS settings"
# aws s3api --endpoint http://localhost:8000 put-bucket-cors --bucket media-local --cors-configuration file:///scripts/cors.json

exit 0